AWSTemplateFormatVersion: 2010-09-09
Description: Creates the project's deployment infrastructure
Resources:

    #-------------------------------------------------------------------------------------------------------------------
    # Elastic Container Registry
    #-------------------------------------------------------------------------------------------------------------------
    EcrRepository:
        Type: 'AWS::ECR::Repository'
        Properties:
            RepositoryName: singleton
            RepositoryPolicyText:
                Version: '2012-10-17'
                Statement:
                    -   Sid: AllowPushPull
                        Effect: 'Allow'
                        Principal: "*"
                        Action:
                            -   'ecr:BatchCheckLayerAvailability'
                            -   'ecr:BatchGetImage'
                            -   'ecr:CompleteLayerUpload'
                            -   'ecr:GetDownloadUrlForLayer'
                            -   'ecr:InitiateLayerUpload'
                            -   'ecr:PutImage'
                            -   'ecr:UploadLayerPart'


