AWSTemplateFormatVersion: 2010-09-09
Description: Creates the project's deployment infrastructure
Resources:

    #-------------------------------------------------------------------------------------------------------------------
    # Networking
    #
    # A simple VPC with a primary and redundant public subnet. While it would be more ideal to host this in a private
    # subnet, it would also cost more for a NAT. The tradeoff is that the public subnet will make the infrastructure
    # subject to more security risks. We can mitigate most of these risks with a security group that will deny all
    # ingress traffic.
    #-------------------------------------------------------------------------------------------------------------------
    VPC:
        Type: 'AWS::EC2::VPC'
        Properties:
            CidrBlock: 10.0.0.0/16

    InternetGateway:
        Type: 'AWS::EC2::InternetGateway'

    AttachGateway:
        Type: 'AWS::EC2::VPCGatewayAttachment'
        Properties:
            VpcId: !Ref VPC
            InternetGatewayId: !Ref InternetGateway

    PublicRouteTable:
        Type: 'AWS::EC2::RouteTable'
        Properties:
            VpcId: !Ref VPC

    PublicRoute:
        Type: 'AWS::EC2::Route'
        DependsOn: AttachGateway
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: '0.0.0.0/0'
            GatewayId: !Ref InternetGateway

    PublicSubnet1:
        Type: 'AWS::EC2::Subnet'
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.0.1.0/28
            AvailabilityZone: us-east-1a

    SubnetRouteTableAssociation1:
        Type: 'AWS::EC2::SubnetRouteTableAssociation'
        Properties:
            SubnetId: !Ref PublicSubnet1
            RouteTableId: !Ref PublicRouteTable

    PublicSubnet2:
        Type: 'AWS::EC2::Subnet'
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.0.2.0/28
            AvailabilityZone: us-east-1b

    SubnetRouteTableAssociation2:
        Type: 'AWS::EC2::SubnetRouteTableAssociation'
        Properties:
            SubnetId: !Ref PublicSubnet2
            RouteTableId: !Ref PublicRouteTable

    #-------------------------------------------------------------------------------------------------------------------
    # Elastic Container Registry
    #-------------------------------------------------------------------------------------------------------------------
    ECR:
        Type: 'AWS::ECR::Repository'
        Properties:
            RepositoryName: singleton
            RepositoryPolicyText:
                Version: '2012-10-17'
                Statement:
                    -   Sid: AllowPushPull
                        Effect: 'Allow'
                        Principal: "*"
                        Action:
                            -   'ecr:BatchCheckLayerAvailability'
                            -   'ecr:BatchGetImage'
                            -   'ecr:CompleteLayerUpload'
                            -   'ecr:GetDownloadUrlForLayer'
                            -   'ecr:InitiateLayerUpload'
                            -   'ecr:PutImage'
                            -   'ecr:UploadLayerPart'
