name: Continuous Integration and Delivery

on:
    push:
        branches:
            -   '*'
        tags:
            -   release/v[0-9]+.[0-9]+.[0-9]+

env:
    PROJECT_NAME: singleton

permissions:
    id-token: write

jobs:
    integration:
        runs-on: ubuntu-latest
        outputs:
            IMAGE_NAME: ${{ steps.generate-image-name.outputs.image_name }}
            DEBUGGING: ${{ steps.generate-image-name.outputs.debugging }}
        steps:
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_BUILDSYSTEM_ARN }}
                    aws-region: ${{ secrets.AWS_REGION }}

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Generate Image Name
                id: generate-image-name
                env:
                    IMAGE_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    IMAGE_REPOSITORY: ${{ env.PROJECT_NAME }}
                run: |
                    image_tag=${{ github.ref_name }}-${{ github.sha }}  # TAGs cannot contain slashes.
                    image_tag=${image_tag//\//-}  # e.g. release/v0.0.0-<sha> --> release-v0.0.0-<sha>
                    image_name=$IMAGE_REGISTRY/$IMAGE_REPOSITORY:$image_tag
                    echo "image_name=$image_name" >> "$GITHUB_OUTPUT"
                    echo "image_name=$image_name"
                    echo "debugging=testtest" >> "$GITHUB_OUTPUT"

#            -   name: Build Docker Image
#                run: |
#                    docker build -t ${{ steps.generate-image-name.outputs.image_name }} .
#
#            -   name: Push Docker Image
#                run: |
#                    docker push ${{ steps.generate-image-name.outputs.image_name }}
#                    echo "- Uploaded ${{ steps.generate-image-name.outputs.image_name }}" >> $GITHUB_STEP_SUMMARY
    test:
        runs-on: ubuntu-latest
        needs: integration
        steps:
            -   name: Testing
                run: |
                    echo ${{ needs.integration.outputs.DEBUGGING }}
                    echo ${{ needs.integration.outputs.IMAGE_NAME }}

    delivery:
        runs-on: ubuntu-latest
        needs: integration
        if: startsWith(github.ref, 'refs/tags/release')
        steps:
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_BUILDSYSTEM_ARN }}
                    aws-region: ${{ secrets.AWS_REGION }}

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Render ECS Task Definition
                id: render-ecs-task-definition
                env:
                    AWS_REGION: ${{ secrets.AWS_REGION }}
                    AWS_ROLE_TASK_EXECUTION_ARN: ${{ secrets.AWS_ROLE_TASK_EXECUTION_ARN }}
                    AWS_ROLE_TASK_ARN: ${{ secrets.AWS_ROLE_TASK_ARN }}
                    AWS_SECRETS_MANAGER_ARN: ${{ secrets.AWS_SECRETS_MANAGER_ARN }}
                    IMAGE_NAME: ${{ needs.integration.outputs.IMAGE_NAME }}
                run: |
                    echo ${{ needs.integration.outputs.IMAGE_NAME }}
                    envsubst < ecs-task-definition.yaml > rendered-ecs-task-definition.yaml
                    echo "task_definition=rendered-ecs-task-definition.yaml" >> "$GITHUB_OUTPUT"

            -   name: Deploy ECS Task Definition
                uses: aws-actions/amazon-ecs-deploy-task-definition@v1
                with:
                    task-definition: ${{ steps.render-ecs-task-definition.outputs.task_definition }}
                    cluster: ${{ env.PROJECT_NAME }}
                    service: ${{ env.PROJECT_NAME }}
                    wait-for-service-stability: true
