name: Continuous Delivery

on:
    push:
        branches:
            - '**'

env:
    PROJECT_NAME: singleton

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            -    name: Checkout Code
                 uses: actions/checkout@v3

            -    name: Build the container
                 run: |
                       docker build -t ${{ env.PROJECT_NAME }} .
