name: Continuous Delivery

on:
    push:
        branches:
            - '**'

env:
    PROJECT_NAME: singleton

jobs:
    infrastructure:
        runs-on: ubuntu-latest
        outputs:
            stack-exists: ${{ steps.check-stack.output.exists }}
        permissions:
            id-token: write
            contents: read
        steps:
            -    name: Checkout Code
                 uses: actions/checkout@v3

            -    name: Configure AWS Credentials
                 uses: aws-actions/configure-aws-credentials@v4
                 with:
                     role-to-assume: ${{ secrets.AWS_ROLE_ARN_BUILDSYSTEM }}
                     aws-region: ${{ secrets.AWS_REGION }}

            -   name: Deploy to AWS CloudFormation
                uses: aws-actions/aws-cloudformation-github-deploy@v1
                with:
                    name: ${{ env.PROJECT_NAME }}
                    template: infrastructure/main.yaml
                    no-fail-on-empty-changeset: "1"
